### ISSUE TITLE
Run Testing script in docker failed (KeyError)

### ISSUE THREAD

**Issue by GJChen919** [lyltc1/HiPose#8]
Hi I run the testing script following Readme
Unfortunetly, I got the KeyError:15 in get_bop_challange_test_data
Anyone know how to fix it?

```
root@173eee14b96c:/home/HiPose/hipose# python test.py --cfg config/test_lmo_config.txt --obj_name ape --ckpt_file ~/HiPose/data/lmo/check_point/lmo/lmo_convnext_mega6d_stream_ape/best_score/0_7824step86000 --eval_output ~/HiPose/output/eval_lmo_output --new_solver_version True --region_bit 10

bop_challange  :  True 
bop_path  :  /home/HiPose/data/
dataset_name  :  lmo
training_data_folder  :  train_pbr
training_data_folder_2  :  none
val_folder  :  test
test_folder  :  test
second_dataset_ratio  :  0.75
num_workers  :  8
train_obj_visible_theshold  :  0.2
BoundingBox_CropSize_image  :  256
BinaryCode_Loss_Type  :  BCE
mask_binary_code_loss  :  True
use_histgramm_weighted_binary_loss  :  False
fusion  :  False
convnext  :  convnext_base
load_checkpoint  :  False
check_point_path  :  /home/6dof_pose_experiments/hipose/lmo_bop/checkpoints/
tensorboard_path  :  /home/6dof_pose_experiments/hipose/lmo_bop/tensorboard_logs/runs/
optimizer_type  :  Adam
learning_rate  :  0.0001
use_lr_scheduler  :  False
batch_size  :  32
total_iteration  :  380000
binary_loss_weight  :  3
Detection_reaults  :  /home/HiPose/hipose/detection_results/gdrnpp/gdrnppdet-pbrreal_lmo-test_202a2f15-cbd0-49df-90de-650428c6d157.json
padding_ratio  :  1.5
resize_method  :  crop_square_resize
use_peper_salt  :  True
use_motion_blur  :  True
aug_depth  :  False
aug_depth_megapose6d  :  False
interpolate_depth  :  False
shift_center  :  False
shift_from_center  :  False
divide_number_each_itration  :  2
number_of_itration  :  16
detector  :  MASKRCNN
obj_name  :  ape
new_solver_version  :  True
region_bit  :  10
checkpoint_file  :  ~/HiPose/data/lmo/check_point/lmo/lmo_convnext_mega6d_stream_ape/best_score/0_7824step86000
eval_output_path  :  ~/HiPose/output/eval_lmo_output
/opt/conda/lib/python3.10/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
/home/HiPose/data/lmo/models/obj_000001.ply
/home/HiPose/data/lmo/models/obj_000002.ply
/home/HiPose/data/lmo/models/obj_000003.ply
/home/HiPose/data/lmo/models/obj_000004.ply
/home/HiPose/data/lmo/models/obj_000005.ply
/home/HiPose/data/lmo/models/obj_000006.ply
/home/HiPose/data/lmo/models/obj_000007.ply
/home/HiPose/data/lmo/models/obj_000008.ply
/home/HiPose/data/lmo/models/obj_000009.ply
/home/HiPose/data/lmo/models/obj_000010.ply
/home/HiPose/data/lmo/models/obj_000011.ply
/home/HiPose/data/lmo/models/obj_000012.ply
/home/HiPose/data/lmo/models/obj_000013.ply
/home/HiPose/data/lmo/models/obj_000014.ply
/home/HiPose/data/lmo/models/obj_000015.ply
if models are not fully listed above, please make sure there are ply files available
obj_diameter 102.099
use BOP test images
get_bop_challange_test_data
Traceback (most recent call last):
  File "/home/HiPose/hipose/test.py", line 442, in <module>
    main(configs)
  File "/home/HiPose/hipose/test.py", line 279, in main
    dataset_dir_test,bop_test_folder,_,_,_,test_rgb_files,test_depth_files,test_mask_files,test_mask_visib_files,test_gts,test_gt_infos,_, camera_params_test = bop_io.get_bop_challange_test_data(bop_path, dataset_name, target_obj_id=obj_id+1, data_folder=test_folder)
  File "/home/HiPose/hipose/tools_for_BOP/bop_io.py", line 67, in get_bop_challange_test_data
    gts = scene_gts[im_id]
KeyError: 15```

**Comment by GJChen919** [comment]
I change the code in test.py (line 275), and can run evaluation without BOP challange test.
Will research how to run BOP challange test.

**Comment by lyltc1** [comment]
Hi, it seems the problem comes from the dataset part. So to debug what happened, try to print `scene_gts.keys()` to see why `im_id=15` is not in the `scene_gts` and also to investigate the construction process of `scene_gts` in the code, to see what issues occurred when `im_id=15` was being added to `scene_gts`.

**Comment by GJChen919** [comment]
Thank you, I re-downloaded the test data, and all is done.
