### ISSUE TITLE
Errors related to incorrect paths to some image files in the dataset or file formats that are not as expected

### ISSUE THREAD

**Issue by liiijee-163** [lyltc1/HiPose#9]
Hello, I ran into this problem while working on this project reproduction:

bop_challange  :  False
bop_path  :  /home/liiijee/HiPose/data
dataset_name  :  lmo
training_data_folder  :  train_pbr
training_data_folder_2  :  none
val_folder  :  test
test_folder  :  test
second_dataset_ratio  :  0.75
num_workers  :  0
train_obj_visible_theshold  :  0.2
BoundingBox_CropSize_image  :  256
BinaryCode_Loss_Type  :  BCE
mask_binary_code_loss  :  True
use_histgramm_weighted_binary_loss  :  False
fusion  :  False
convnext  :  convnext_large
load_checkpoint  :  False
check_point_path  :  /home/liiijee/HiPose/output/exp/lmo/checkpoints/train_lmo_config_ape/
tensorboard_path  :  /home/liiijee/HiPose/output/exp/lmo/tensorboard_logs/runs/train_lmo_config_ape/
optimizer_type  :  Adam
learning_rate  :  0.0001
use_lr_scheduler  :  False
batch_size  :  32
total_iteration  :  380000
binary_loss_weight  :  3
Detection_reaults  :  /home/liiijee/HiPose/hipose/detection_results/gdrnpp/yolox_x_640_lmo_pbr_lmo_bop_test.json
padding_ratio  :  1.5
resize_method  :  crop_square_resize
use_peper_salt  :  True
use_motion_blur  :  True
aug_depth  :  False
aug_depth_megapose6d  :  False
interpolate_depth  :  False
shift_center  :  False
shift_from_center  :  False
divide_number_each_itration  :  2
number_of_itration  :  16
detector  :  FCOS
obj_name  :  ape
sym_aware_training  :  False
config_file_name  :  train_lmo_config
/home/liiijee/anaconda3/envs/hipose_env/lib/python3.10/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
/home/liiijee/HiPose/data/lmo/models/obj_000001.ply
/home/liiijee/HiPose/data/lmo/models/obj_000002.ply
/home/liiijee/HiPose/data/lmo/models/obj_000003.ply
/home/liiijee/HiPose/data/lmo/models/obj_000004.ply
/home/liiijee/HiPose/data/lmo/models/obj_000005.ply
/home/liiijee/HiPose/data/lmo/models/obj_000006.ply
/home/liiijee/HiPose/data/lmo/models/obj_000007.ply
/home/liiijee/HiPose/data/lmo/models/obj_000008.ply
/home/liiijee/HiPose/data/lmo/models/obj_000009.ply
/home/liiijee/HiPose/data/lmo/models/obj_000010.ply
/home/liiijee/HiPose/data/lmo/models/obj_000011.ply
/home/liiijee/HiPose/data/lmo/models/obj_000012.ply
/home/liiijee/HiPose/data/lmo/models/obj_000013.ply
/home/liiijee/HiPose/data/lmo/models/obj_000014.ply
/home/liiijee/HiPose/data/lmo/models/obj_000015.ply
if models are not fully listed above, please make sure there are ply files available
/home/liiijee/HiPose/data/lmo/models/obj_000001.ply
obj_diameter 102.099
Loaded 37801 RGB images for obj_id 0.
training_data_folder image example: /home/liiijee/HiPose/data/lmo/train_pbr/000016/rgb/000000.jpg
/home/liiijee/HiPose/data/lmo/models/obj_000001.ply
/home/liiijee/HiPose/data/lmo/models/obj_000002.ply
/home/liiijee/HiPose/data/lmo/models/obj_000003.ply
/home/liiijee/HiPose/data/lmo/models/obj_000004.ply
/home/liiijee/HiPose/data/lmo/models/obj_000005.ply
/home/liiijee/HiPose/data/lmo/models/obj_000006.ply
/home/liiijee/HiPose/data/lmo/models/obj_000007.ply
/home/liiijee/HiPose/data/lmo/models/obj_000008.ply
/home/liiijee/HiPose/data/lmo/models/obj_000009.ply
/home/liiijee/HiPose/data/lmo/models/obj_000010.ply
/home/liiijee/HiPose/data/lmo/models/obj_000011.ply
/home/liiijee/HiPose/data/lmo/models/obj_000012.ply
/home/liiijee/HiPose/data/lmo/models/obj_000013.ply
/home/liiijee/HiPose/data/lmo/models/obj_000014.ply
/home/liiijee/HiPose/data/lmo/models/obj_000015.ply
if models are not fully listed above, please make sure there are ply files available
test_rgb_file exsample /home/liiijee/HiPose/data/lmo/test/000002/rgb/000003.png
number of test images:  182
binary_code_length:  16
Traceback (most recent call last):
  File "/home/liiijee/HiPose/hipose/train.py", line 439, in <module>
    main(configs)
  File "/home/liiijee/HiPose/hipose/train.py", line 285, in main
    for batch_idx, (inputs, targets) in enumerate(train_loader): #通过enumerate方法从训练数据集中批量读取数据
  File "/home/liiijee/anaconda3/envs/hipose_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/liiijee/anaconda3/envs/hipose_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/liiijee/anaconda3/envs/hipose_env/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liiijee/anaconda3/envs/hipose_env/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liiijee/HiPose/hipose/bop_dataset_3d_convnext_backbone.py", line 403, in __getitem__
    x = self.apply_augmentation(x)
  File "/home/liiijee/HiPose/hipose/bop_dataset_3d_convnext_backbone.py", line 658, in apply_augmentation
    x = augmentations.augment_image(x)
  File "/home/liiijee/anaconda3/envs/hipose_env/lib/python3.10/site-packages/imgaug/augmenters/meta.py", line 763, in augment_image
    "Expected to get a single numpy array of shape (H,W) or (H,W,C) "
TypeError: %d format: a real number is required, not str

it looks as if it's a file path problem or a file format problem.
 My data structure is as follows:
![image](https://github.com/user-attachments/assets/6e84b56b-c220-4083-ae67-bff33b06249d)
My data structure for train_pbr and test is as follows:
![image](https://github.com/user-attachments/assets/62d7826e-7ba2-4908-8823-7c792e85fd53)

**Comment by lyltc1** [comment]
Please check the type and shape of `x` in the file "/home/liiijee/HiPose/hipose/bop_dataset_3d_convnext_backbone.py" at line 658, where `x` is passed to `augmentations.augment_image(x)`. If `x` is `None`, trace back to where `x` is initialized. If `x` is not a single numpy array with shape `(H, W)` or `(H, W, C)`, it’s possible that imgaug has been updated. In that case, try uninstalling the current version and installing an older one. Looking forward to hearing about your progress!

**Comment by liiijee-163** [comment]
Thanks for your reply, I found out what my problem was, it was because of a problem with the numpy module.
